{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sql-exporter.fullname" . }}
  labels:
    {{- include "sql-exporter.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "sql-exporter.annotations" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations}}
      {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ default "false" .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
