{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sql-exporter.serviceAccountName" . }}
  {{- with .Values.serviceAccount.annotations}}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "sql-exporter.labels" . | nindent 4 }}
automountServiceAccountToken: {{ default "false" .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
